# include ./colors.conf
# include ./theme.conf

# Fonts
font_family           JetBrainsMono Nerd Font Bold
italic_font           JetBrainsMono Nerd Font Bold Italic
bold_font             JetBrainsMono Nerd Font Extra Bold
bold_italic_font      JetBrainsMono Nerd Font Extra Bold Italic
font_size             10
background_opacity    0.95

# enabled_layouts tall:bias=50;full_size=1;mirrored=false
# The width (in pts) of window borders. Will be rounded to the nearest number of pixels based on screen resolution.
# Note that borders are displayed only when more than one window is visible. They are meant to separate multiple windows.
window_border_width 2

# The window margin (in pts) (blank area outside the border)
window_margin_width 4

# The window padding (in pts) (blank area between the text and the window border)
window_padding_width 5

# The color for the border of the active window
active_border_color #c4c4c4

# The color for the border of inactive windows
inactive_border_color #474E48

# BEGIN_KITTY_THEME
# Catppuccin
#include kitty-themes/themes/Catppuccin.conf
#include kitty-themes/themes/Bright Lights.conf
include colors.conf
# END_KITTY_THEME
