include ./colors.conf

# Fonts
font_family           JetBrains Mono Medium
italic_font           JetBrains Mono Italic
bold_font             JetBrains Moo Bold
bold_italic_font      JetBrains Mono Bold Italic
font_size             10
background_opacity    0.9
